### PR TITLE
Vue explorer

### LINKED ISSUE #442: Search result map getting mangled
Vinny no like. :cry: 

screenshot_2018-08-21 plenario

### PR DESCRIPTION
**Pull request by HeyZoos**
While there are a variety of usability issues and bugs present, I'd like to get the application deployed onto our development server so that we can see how it does with our real datasets. The outstanding issues I'll convert into github issues instead of chipping away at them by myself. 

For starters the search page has gotten a fantastic overhaul thanks to @brlodi. He's also taken the time to get our production build into snappy ~240KB chunks, as well as setting us up with the proper tooling. 

This PR introduces __Yarn__ to replace NPM. We were having issues with different NPM versions across different operating systems flipping our dependency versions for unknown reasons. This would result in very large diffs that only served to obfuscate important changes. We have not encountered this issue with Yarn, so hopefully that should be the end of that.

We also chose to replace chart.js with the much more lightweight __chartist.js__. 

__Known Issues__

- If you resize the window just right, the leaflet map leaps out of its container in an ugly fashion. We've known about this for a little while, I've just been prioritizing the new functionality and haven't gotten around to it.
- Compare map just chooses a random color when you plot points on the map, and doesn't indicate which color belongs to which dataset. This color also does not match with the color of the lines plotted on the charts. 
- Lots of little aesthetic inconsistencies, mostly due to my inexperience like things not being centered properly in the tables.
- The compare page isn't really responsive to different page sizes, the space could be better used if both the map and charts were shown on larger screens. 
- The bbox on the compare page is pretty gross, I'm going to try and replicate the trick @brlodi had implemented for the ember app and fade out the area of the map outside of the bbox.
- Probably a billion other things, that's why it'd be great to start having people poke around.

__Backwards Incompatible Changes__

- I removed the one of the helpers for server rendered charts. This is the start of the frontend application assuming all of the charting responsibilities. I really didn't like that we had backend code dedicated to strictly frontend responsibilities like rendering charts & managing a color palette. Eventually that'll all get eaten by the vue app.

- Added an `aggregate` endpoint, totally just jammed it in and it's untested. It issues a query to bucket search results and returns json. The meta information isn't populated, the results are all just placed into the `data` property. This of course will change, but I just needed the shape of the response to be correct and didn't care about the meta information.

Closes #442 #441 #373 

__Search__ @ `/explore` 

search

__Search Results__ @ `/explore`

results

__Plotting Results to map__ @ `/compare`

mapping

__Charting Results to Map__ @ `/compare`

charting

### CODE REVIEW

**Comment by brlodi** [comment]
Looking good! If you can handle waiting until the end of the week, I can probably help sort out some of the styling oddness come Thursday and Friday.

**Comment by vforgione** [comment]
Data set detail pages also don't push the status forward -- if someone requests `/data-sets/i don't exist` the controller responds with a 404 but the vue app sends a 200 with an error in the HTML.

**Comment by HeyZoos** [comment]
The failing tests are for the `/data-set/:slug` views. I removed the auth plug from them because I felt anyone should be able to at least see details about the data set even if they aren't signed in.

**Comment by vforgione** [comment]
Right, but by removing it you give anyone access to then also edit those entries. We need to substitute the original permission with something that allows anons and non-owners to view the entry and only admins and owners to edit them.

**Comment by HeyZoos** [comment]
Are you sure? Because that's not the behavior I'm observing.

Anonymous / No-ownership
image

Owned
image

The :auth plug only ensures a user is logged in. The `Canada.can` permissions seem to be something separate

```elixir
  defimpl Canada.Can, for: Atom do

    @doc """
    Anonymous users can only access the :index and :show actions of
    Metas, Users, Charts and ChartDatasets.
    """
    def can?(nil, action, %Meta{}) when action in [:index, :show], do: true
    def can?(nil, action, %User{}) when action in [:index, :show], do: true
    def can?(nil, action, %ChartDataset{}) when action in [:show, :list], do: true
    def can?(nil, action, %Chart{}) when action in [:show, :list, :render_chart], do: true
    def can?(nil, _, _), do: false
  end

  defimpl Canada.Can, for: User do

    @doc """
    Admin users can perform any action, regardless of who owns the resource.
    """
    def can?(%User{is_admin: true}, _, _), do: true

    @doc """
    Authenticated users can only access the Meta index and show, unless they
    are the owner of the Meta.
    """
    def can?(%User{id: user_id}, _, %Meta{user_id: user_id}), do: true
    def can?(%User{}, action, Meta) when action in [:new, :create], do: true
    def can?(%User{}, action, %Meta{}) when action in [:show], do: true
    def can?(%User{}, _, %Meta{}), do: false
```

**Comment by HeyZoos** [comment]
I understand, I misinterpreted the visibility of the edit buttons as permissions acting how I expected. Those are just based on a superficial check of ownership, but users can still edit each other's datasets. I'll work on updating the permissions & tests.

**Comment by vforgione** [comment]
I just opened a PR to fix the auth stuff -- #449

**Comment by HeyZoos** [comment]
Just saw that, big thanks.

**Pull request merged**
